web:
  appname: spring-petclinic
  repo: elevy99927
  image: spring-petclinic
  tag: latest
  port: 8080
mysql:
  appname: spring-mysql
  repo: docker.io
  image: mysql
  tag: 5.7
  port: 3306
  env:
    root_password: 1234
    allow_empty_password: true
    user: petclinic
    db_password: petclinic
    db_name: petclinic

